# Generated by Django 2.0.3 on 2018-03-28 11:03

from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='devicelocation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.Location'),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100,blank=True,null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='location',
            name='is_mobile',
            field=models.BooleanField(help_text='is this location a moving object?', verbose_name='is mobile?'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(blank=True, choices=[('outdoor', 'Outdoor environment (eg: street, square, garden, land)'), ('indoor', 'Indoor environment (eg: building, roofs, subway, large vehicles)')], help_text='indoor locations can have floorplans associated to them', max_length=8, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='floorplan',
            unique_together={('location', 'floor')},
        ),
        migrations.RunSQL("update geo_location set geolocation='41.90278349999999,12.496365500000024' where geolocation = 'geolocation' and is_mobile=0"),
        migrations.RunSQL("update geo_location set geolocation='' where geolocation = 'geolocation' and is_mobile=1"),
    ]
